/* Generated by CCAN configurator

A config.h is needed for the isaac and isaac64 generators, and ought to be
automatically generated when you try to compile those (e.g. with `make` or
`make isaac64.so`).  If for some reason that doesn't work, you could move
copy or symlink this file into place and check that it is approximately right
for your computer.
 */
#ifndef CCAN_CONFIG_H
#define CCAN_CONFIG_H

#ifndef _GNU_SOURCE
#define _GNU_SOURCE /* Always use GNU extensions. */
#endif

#define CCAN_COMPILER "cc"
#define CCAN_CFLAGS "-g -Wall -Wundef -Wmissing-prototypes -Wmissing-declarations -Wstrict-prototypes -Wold-style-definition -O3"

#define HAVE_ALIGNOF 1
#define HAVE_ASPRINTF 1
#define HAVE_ATTRIBUTE_COLD 1
#define HAVE_ATTRIBUTE_CONST 1
#define HAVE_ATTRIBUTE_MAY_ALIAS 1
#define HAVE_ATTRIBUTE_NORETURN 1
#define HAVE_ATTRIBUTE_PRINTF 1
#define HAVE_ATTRIBUTE_UNUSED 1
#define HAVE_ATTRIBUTE_USED 1
#define HAVE_BIG_ENDIAN 0
#define HAVE_BSWAP_64 1
#define HAVE_BUILTIN_CHOOSE_EXPR 1
#define HAVE_BUILTIN_CLZ 1
#define HAVE_BUILTIN_CLZL 1
#define HAVE_BUILTIN_CLZLL 1
#define HAVE_BUILTIN_CONSTANT_P 1
#define HAVE_BUILTIN_EXPECT 1
#define HAVE_BUILTIN_FFSL 1
#define HAVE_BUILTIN_FFSLL 1
#define HAVE_BUILTIN_POPCOUNTL 1
#define HAVE_BUILTIN_TYPES_COMPATIBLE_P 1
#define HAVE_BYTESWAP_H 1
#define HAVE_COMPOUND_LITERALS 1
#define HAVE_FOR_LOOP_DECLARATION 0
#define HAVE_FLEXIBLE_ARRAY_MEMBER 1
#define HAVE_GETPAGESIZE 1
#define HAVE_ISBLANK 1
#define HAVE_LITTLE_ENDIAN 1
#define HAVE_MEMMEM 1
#define HAVE_MMAP 1
#define HAVE_QSORT_R_PRIVATE_LAST 1
#define HAVE_STACK_GROWS_UPWARDS 0
#define HAVE_STATEMENT_EXPR 1
#define HAVE_TYPEOF 1
#define HAVE_UTIME 1
#define HAVE_WARN_UNUSED_RESULT 1
#endif /* CCAN_CONFIG_H */
